In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
sent=['I love programming', 
      'Python is great', 
      'TensorFlow makes ML easy',
      'Keras is user-friendly',
      'Deep learning is fascinating',
      'Natural Language Processing is amazing',  
]

In [14]:
sent

['I love programming',
 'Python is great',
 'TensorFlow makes ML easy',
 'Keras is user-friendly',
 'Deep learning is fascinating',
 'Natural Language Processing is amazing']

In [15]:
## Define vocabulary size
vocab_size = 10000

In [16]:
##One hot representation
one_hot_repr = [one_hot(sentence, vocab_size) for sentence in sent]
one_hot_repr

[[4404, 5058, 7213],
 [1635, 8540, 3495],
 [5088, 4002, 2668, 9627],
 [6596, 8540, 7351, 4419],
 [8884, 2100, 8540, 9634],
 [3, 351, 7192, 8540, 4347]]

In [17]:
## Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [20]:
sent_length=6
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [21]:
embedded_docs

array([[   0,    0,    0, 4404, 5058, 7213],
       [   0,    0,    0, 1635, 8540, 3495],
       [   0,    0, 5088, 4002, 2668, 9627],
       [   0,    0, 6596, 8540, 7351, 4419],
       [   0,    0, 8884, 2100, 8540, 9634],
       [   0,    3,  351, 7192, 8540, 4347]], dtype=int32)

In [22]:
##feature representation
dim=10

In [23]:
model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=dim, input_length=sent_length))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


C:\Users\hrishizone\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step


array([[[ 1.11048445e-02, -1.87046453e-03, -1.62922032e-02,
          3.34967263e-02, -1.06814876e-02,  4.66717593e-02,
         -4.42469008e-02,  2.84818299e-02, -2.24823840e-02,
         -4.02006507e-02],
        [ 1.11048445e-02, -1.87046453e-03, -1.62922032e-02,
          3.34967263e-02, -1.06814876e-02,  4.66717593e-02,
         -4.42469008e-02,  2.84818299e-02, -2.24823840e-02,
         -4.02006507e-02],
        [ 1.11048445e-02, -1.87046453e-03, -1.62922032e-02,
          3.34967263e-02, -1.06814876e-02,  4.66717593e-02,
         -4.42469008e-02,  2.84818299e-02, -2.24823840e-02,
         -4.02006507e-02],
        [ 9.11734253e-03,  4.40598391e-02, -1.85491890e-03,
          1.93732865e-02, -3.88792530e-02, -2.16577295e-02,
          2.17468999e-02, -4.10689823e-02,  2.41721384e-02,
          4.31368835e-02],
        [-2.79995333e-02, -4.80051748e-02,  4.07641269e-02,
          3.96583341e-02, -1.50282308e-03, -4.62722071e-02,
         -2.73258444e-02, -3.97443883e-02, -5.088496

In [26]:
embedded_docs[0]

array([   0,    0,    0, 4404, 5058, 7213], dtype=int32)